# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  - master
  - develop

pr:
  - master
  - develop

stages:
  - stage: BuildEvogen
    jobs:
      - job: BuildEvogenLinux
        timeoutInMinutes: "0"
        displayName: Linux
        continueOnError: "false"
        pool:
          vmImage: "ubuntu-18.04"

        strategy:
          matrix:
            64-bit Linux Release:
              BuildType: Release
              CMakeArgs: "-DCMAKE_INSTALL_PREFIX=$(Build.BinariesDirectory)/install-azure-release"
            64-bit Linux Debug:
              BuildType: Debug
              CMakeArgs: "-DCMAKE_INSTALL_PREFIX=$(Build.BinariesDirectory)/install-azure-debug"
        steps:
          - task: CMake@1
            displayName: ConfigureCommand
            inputs:
              cmakeArgs: $(CMakeArgs)  -DCMAKE_BUILD_TYPE=$(BuildType) -DBUILD_TESTS=ON ..
          - task: CMake@1
            displayName: BuildCommand
            inputs:
              cmakeArgs: --build . --target install --config $(BuildType) -j 12
          - script: |
              echo "pwd: $(pwd)"
              ls
              echo "$(Agent.BuildDirectory)"
              cd $(Agent.BuildDirectory)/s/build
              echo "pwd: $(pwd)"
              ls
              ctest --verbose --extra-verbose --progress
            displayName: RunTests
            
            
      - job: BuildEvogenWindows
        timeoutInMinutes: "0"
        displayName: Linux
        continueOnError: "false"
        pool:
          vmImage: "windows2019"

        strategy:
          matrix:
            64-bit Windows Release:
              BuildType: Release
              CMakeArgs: "-DCMAKE_INSTALL_PREFIX=$(Build.BinariesDirectory)/install-azure-release"
            64-bit Windows Debug:
              BuildType: Debug
              CMakeArgs: "-DCMAKE_INSTALL_PREFIX=$(Build.BinariesDirectory)/install-azure-debug"
        steps:
          - task: CMake@1
            displayName: ConfigureCommand
            inputs:
              cmakeArgs: $(CMakeArgs)  -DCMAKE_BUILD_TYPE=$(BuildType) -DBUILD_TESTS=ON ..
          - task: CMake@1
            displayName: BuildCommand
            inputs:
              cmakeArgs: --build . --target install --config $(BuildType) -j 12
          - script: |
              echo "pwd: $(pwd)"
              ls
              echo "$(Agent.BuildDirectory)"
              cd $(Agent.BuildDirectory)/s/build
              echo "pwd: $(pwd)"
              ls
              ctest --verbose --extra-verbose --progress
            displayName: RunTests
      - job: BuildEvogenMac
        timeoutInMinutes: "0"
        displayName: Mac
        continueOnError: "false"
        pool:
          vmImage: "macOS-10.15"

        strategy:
          matrix:
            64-bit Mac Release:
              BuildType: Release
              CMakeArgs: "-DCMAKE_INSTALL_PREFIX=$(Build.BinariesDirectory)/install-azure-release"
            64-bit Mac Debug:
              BuildType: Debug
              CMakeArgs: "-DCMAKE_INSTALL_PREFIX=$(Build.BinariesDirectory)/install-azure-debug"
        steps:
          - task: CMake@1
            displayName: ConfigureCommand
            inputs:
              cmakeArgs: $(CMakeArgs)  -DCMAKE_BUILD_TYPE=$(BuildType) -DBUILD_TESTS=ON ..
          - task: CMake@1
            displayName: BuildCommand
            inputs:
              cmakeArgs: --build . --target install --config $(BuildType) -j 12
          - script: |
              echo "pwd: $(pwd)"
              ls
              echo "$(Agent.BuildDirectory)"
              cd $(Agent.BuildDirectory)/s/build
              echo "pwd: $(pwd)"
              ls
              ctest --verbose --extra-verbose --progress
            displayName: RunTests

